//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatAmIHearing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhatAmIHearing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get an API Key, follow these instructions:.
        /// </summary>
        public static string ApiKeyInstructions {
            get {
                return ResourceManager.GetString("ApiKeyInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        public static string ApiKeyLabel {
            get {
                return ResourceManager.GetString("ApiKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Settings.
        /// </summary>
        public static string ApiSettingsHeader {
            get {
                return ResourceManager.GetString("ApiSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel recording.
        /// </summary>
        public static string CancelStopBehavior {
            get {
                return ResourceManager.GetString("CancelStopBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Input Device.
        /// </summary>
        public static string DefaultInputDeviceName {
            get {
                return ResourceManager.GetString("DefaultInputDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Output Device.
        /// </summary>
        public static string DefaultOutputDeviceName {
            get {
                return ResourceManager.GetString("DefaultOutputDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display input devices in device dropdown.
        /// </summary>
        public static string DisplayInputDevicesCheckboxLabel {
            get {
                return ResourceManager.GetString("DisplayInputDevicesCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter hotkey (ESC to clear).
        /// </summary>
        public static string EnterHotkeyInstructions {
            get {
                return ResourceManager.GetString("EnterHotkeyInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move settings file..
        /// </summary>
        public static string FailedToMoveSettingsFileErrorText {
            get {
                return ResourceManager.GetString("FailedToMoveSettingsFileErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray after recording is done.
        /// </summary>
        public static string HideAfterRecordingCheckboxLabel {
            get {
                return ResourceManager.GetString("HideAfterRecordingCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryHeader {
            get {
                return ResourceManager.GetString("HistoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Devices.
        /// </summary>
        public static string InputDevicesHeader {
            get {
                return ResourceManager.GetString("InputDevicesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep open in system tray.
        /// </summary>
        public static string KeepOpenInTrayCheckboxLabel {
            get {
                return ResourceManager.GetString("KeepOpenInTrayCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When closing this window, WhatAmIHearing will continue to run in the background and can be accessed from the system tray.
        /// </summary>
        public static string KeepOpenInTrayCheckboxToolTip {
            get {
                return ResourceManager.GetString("KeepOpenInTrayCheckboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch hidden.
        /// </summary>
        public static string LaunchHiddenCheckboxLabel {
            get {
                return ResourceManager.GetString("LaunchHiddenCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatAmIHearing will launch hidden, accessible from the system tray.
        /// </summary>
        public static string LaunchHiddenCheckboxToolTip {
            get {
                return ResourceManager.GetString("LaunchHiddenCheckboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch on Windows startup.
        /// </summary>
        public static string LaunchOnWindowsStartupCheckboxLabel {
            get {
                return ResourceManager.GetString("LaunchOnWindowsStartupCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record {0}% of allowed audio.
        /// </summary>
        public static string LimitAudioRecordingLabel {
            get {
                return ResourceManager.GetString("LimitAudioRecordingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hotkey set.
        /// </summary>
        public static string NoHotkeySetText {
            get {
                return ResourceManager.GetString("NoHotkeySetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically open identified song in Shazam.
        /// </summary>
        public static string OpenShazamCheckboxLabel {
            get {
                return ResourceManager.GetString("OpenShazamCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a successful song identification, WhatAmIHearing will automatically open the song&apos;s page in Shazam.
        /// </summary>
        public static string OpenShazamCheckboxToolTip {
            get {
                return ResourceManager.GetString("OpenShazamCheckboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Devices.
        /// </summary>
        public static string OutputDevicesHeader {
            get {
                return ResourceManager.GetString("OutputDevicesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Display:.
        /// </summary>
        public static string ProgressDisplayLabel {
            get {
                return ResourceManager.GetString("ProgressDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place song title on clipboard after identification.
        /// </summary>
        public static string PutTitleOnClipboardCheckboxLabel {
            get {
                return ResourceManager.GetString("PutTitleOnClipboardCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota:.
        /// </summary>
        public static string QuotaLabel {
            get {
                return ResourceManager.GetString("QuotaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota values are updated after every audio identification.
        /// </summary>
        public static string QuotaToolTip {
            get {
                return ResourceManager.GetString("QuotaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder Settings.
        /// </summary>
        public static string RecorderSettingsHeader {
            get {
                return ResourceManager.GetString("RecorderSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Hotkey:.
        /// </summary>
        public static string RecordHotkeyLabel {
            get {
                return ResourceManager.GetString("RecordHotkeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send recorded audio (min 20%).
        /// </summary>
        public static string SendStopBehavior {
            get {
                return ResourceManager.GetString("SendStopBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save app settings in user settings folder.
        /// </summary>
        public static string SettingsLocationCheckboxLabel {
            get {
                return ResourceManager.GetString("SettingsLocationCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked: Settings are saved in Roaming AppData (Tied to system and user)&amp;#x0a;Unchecked: Settings are saved in the same folder as the exe (Self-contained and portable).
        /// </summary>
        public static string SettingsLocationCheckboxToolTip {
            get {
                return ResourceManager.GetString("SettingsLocationCheckboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens when stopping a recording.
        /// </summary>
        public static string StopBehaviorComboBoxToolTip {
            get {
                return ResourceManager.GetString("StopBehaviorComboBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Behavior:.
        /// </summary>
        public static string StopBehaviorLabel {
            get {
                return ResourceManager.GetString("StopBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep window on top.
        /// </summary>
        public static string TopmostWindowCheckboxLabel {
            get {
                return ResourceManager.GetString("TopmostWindowCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatAmIHearing will attempt to always stay above other windows.
        /// </summary>
        public static string TopmostWindowCheckboxToolTip {
            get {
                return ResourceManager.GetString("TopmostWindowCheckboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Spotify links in Spotify app.
        /// </summary>
        public static string UseSpotifyAppCheckboxLabel {
            get {
                return ResourceManager.GetString("UseSpotifyAppCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to use the browser or Spotify app to open Spotify links.
        /// </summary>
        public static string UseSpotifyAppCheckboxToolTip {
            get {
                return ResourceManager.GetString("UseSpotifyAppCheckboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using default API Key.
        /// </summary>
        public static string UsingDefaultApiKey {
            get {
                return ResourceManager.GetString("UsingDefaultApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Settings.
        /// </summary>
        public static string WindowSettingsHeader {
            get {
                return ResourceManager.GetString("WindowSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Am I Hearing?.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
